name: UpdateScores
on:
  push:
    branches: [ "master" ]
    paths:
      - 'TarotGG.csv'
  pull_request:
    branches: [ "master" ]
    paths:
      - 'TarotGG.csv'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
        
    # Install the .NET
    - name: Install .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x
        
    # Execute all
    - name: Run script
      run: dotnet run
      
    - name: Commit files # transfer the new html files back into the repository
      run: |
        git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git add ./output
        git commit -m "Update !"
        
    - name: Push changes # push the output folder to your repo
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
